// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContactsByUserID = `-- name: GetContactsByUserID :many
SELECT id, user_id, phone, name, created_at FROM contacts WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetContactsByUserID(ctx context.Context, userID int64) ([]Contact, error) {
	rows, err := q.db.Query(ctx, getContactsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Phone,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContact = `-- name: UpsertContact :one
INSERT INTO contacts (user_id, phone, name)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, phone) DO UPDATE
SET name = EXCLUDED.name
RETURNING id, user_id, phone, name, created_at
`

type UpsertContactParams struct {
	UserID int64       `json:"user_id"`
	Phone  string      `json:"phone"`
	Name   pgtype.Text `json:"name"`
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, upsertContact, arg.UserID, arg.Phone, arg.Name)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const upsertContactBatch = `-- name: UpsertContactBatch :exec
INSERT INTO contacts (user_id, phone, name)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, phone) DO UPDATE
SET name = EXCLUDED.name
`

type UpsertContactBatchParams struct {
	UserID int64       `json:"user_id"`
	Phone  string      `json:"phone"`
	Name   pgtype.Text `json:"name"`
}

func (q *Queries) UpsertContactBatch(ctx context.Context, arg UpsertContactBatchParams) error {
	_, err := q.db.Exec(ctx, upsertContactBatch, arg.UserID, arg.Phone, arg.Name)
	return err
}
