// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rule.sql

package db

import (
	"context"
)

const getRuleByUserID = `-- name: GetRuleByUserID :one
SELECT id, user_id, config, updated_at FROM rules WHERE user_id = $1
`

func (q *Queries) GetRuleByUserID(ctx context.Context, userID int64) (Rule, error) {
	row := q.db.QueryRow(ctx, getRuleByUserID, userID)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Config,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRule = `-- name: UpsertRule :one
INSERT INTO rules (user_id, config, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (user_id) DO UPDATE
SET config = $2, updated_at = NOW()
RETURNING id, user_id, config, updated_at
`

type UpsertRuleParams struct {
	UserID int64  `json:"user_id"`
	Config []byte `json:"config"`
}

func (q *Queries) UpsertRule(ctx context.Context, arg UpsertRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, upsertRule, arg.UserID, arg.Config)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Config,
		&i.UpdatedAt,
	)
	return i, err
}
