// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (user_id, token, expires_at, token_type, client_ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token, expires_at, is_revoked, token_type, client_ip, user_agent, created_at, last_used_at
`

type CreateTokenParams struct {
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	TokenType string             `json:"token_type"`
	ClientIp  pgtype.Text        `json:"client_ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.TokenType,
		arg.ClientIp,
		arg.UserAgent,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.TokenType,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens, expiresAt)
	return err
}

const getTokenByToken = `-- name: GetTokenByToken :one
SELECT id, user_id, token, expires_at, is_revoked, token_type, client_ip, user_agent, created_at, last_used_at FROM tokens WHERE token = $1
`

func (q *Queries) GetTokenByToken(ctx context.Context, token string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByToken, token)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.TokenType,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE tokens SET is_revoked = true WHERE user_id = $1
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeAllUserTokensByType = `-- name: RevokeAllUserTokensByType :exec
UPDATE tokens SET is_revoked = true WHERE user_id = $1 AND token_type = $2
`

type RevokeAllUserTokensByTypeParams struct {
	UserID    int64  `json:"user_id"`
	TokenType string `json:"token_type"`
}

func (q *Queries) RevokeAllUserTokensByType(ctx context.Context, arg RevokeAllUserTokensByTypeParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokensByType, arg.UserID, arg.TokenType)
	return err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE tokens SET is_revoked = true WHERE token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeToken, token)
	return err
}

const updateTokenLastUsed = `-- name: UpdateTokenLastUsed :exec
UPDATE tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateTokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateTokenLastUsed, id)
	return err
}
