// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone, phone_verified, password_hash, name, business_name, city, address)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, phone, password_hash, phone_verified, name, business_name, city, address, location_url, plan, plan_started_at, plan_expires_at, status, created_at, updated_at
`

type CreateUserParams struct {
	Phone         string      `json:"phone"`
	PhoneVerified bool        `json:"phone_verified"`
	PasswordHash  string      `json:"password_hash"`
	Name          pgtype.Text `json:"name"`
	BusinessName  pgtype.Text `json:"business_name"`
	City          pgtype.Text `json:"city"`
	Address       pgtype.Text `json:"address"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Phone,
		arg.PhoneVerified,
		arg.PasswordHash,
		arg.Name,
		arg.BusinessName,
		arg.City,
		arg.Address,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.PhoneVerified,
		&i.Name,
		&i.BusinessName,
		&i.City,
		&i.Address,
		&i.LocationUrl,
		&i.Plan,
		&i.PlanStartedAt,
		&i.PlanExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, password_hash, phone_verified, name, business_name, city, address, location_url, plan, plan_started_at, plan_expires_at, status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.PhoneVerified,
		&i.Name,
		&i.BusinessName,
		&i.City,
		&i.Address,
		&i.LocationUrl,
		&i.Plan,
		&i.PlanStartedAt,
		&i.PlanExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, password_hash, phone_verified, name, business_name, city, address, location_url, plan, plan_started_at, plan_expires_at, status, created_at, updated_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.PhoneVerified,
		&i.Name,
		&i.BusinessName,
		&i.City,
		&i.Address,
		&i.LocationUrl,
		&i.Plan,
		&i.PlanStartedAt,
		&i.PlanExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, phone, password_hash, phone_verified, name, business_name, city, address, location_url, plan, plan_started_at, plan_expires_at, status, created_at, updated_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.PasswordHash,
			&i.PhoneVerified,
			&i.Name,
			&i.BusinessName,
			&i.City,
			&i.Address,
			&i.LocationUrl,
			&i.Plan,
			&i.PlanStartedAt,
			&i.PlanExpiresAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($2, name),
    business_name = COALESCE($3, business_name),
    city = COALESCE($4, city),
    address = COALESCE($5, address),
    location_url = COALESCE($6, location_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, phone, password_hash, phone_verified, name, business_name, city, address, location_url, plan, plan_started_at, plan_expires_at, status, created_at, updated_at
`

type UpdateUserParams struct {
	ID           int64       `json:"id"`
	Name         pgtype.Text `json:"name"`
	BusinessName pgtype.Text `json:"business_name"`
	City         pgtype.Text `json:"city"`
	Address      pgtype.Text `json:"address"`
	LocationUrl  pgtype.Text `json:"location_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.BusinessName,
		arg.City,
		arg.Address,
		arg.LocationUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.PhoneVerified,
		&i.Name,
		&i.BusinessName,
		&i.City,
		&i.Address,
		&i.LocationUrl,
		&i.Plan,
		&i.PlanStartedAt,
		&i.PlanExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPlan = `-- name: UpdateUserPlan :exec
UPDATE users
SET plan = $2,
    plan_started_at = NOW(),
    plan_expires_at = '2099-12-31T23:59:59Z',
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPlanParams struct {
	ID   int64  `json:"id"`
	Plan string `json:"plan"`
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) error {
	_, err := q.db.Exec(ctx, updateUserPlan, arg.ID, arg.Plan)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}
